/**
 * Hyperbolic (p,q,r) Schwarz-triangle tiling generator.
 *
 * Tiles the hyperbolic plane by a triangle with angles π/p, π/q, π/r (requires
 * 1/p+1/q+1/r < 1), generated by reflecting across its three sides. Every
 * vertex has even valence (2p, 2q, 2r), so the result 3-edge-colours and
 * 2-colours cleanly — the triaxial weave fits with no defects.
 *
 * Works directly in the standard hyperboloid model (Minkowski form
 * ⟨u,v⟩ = uₓvₓ + u_yv_y − u_zv_z): the three mirror normals have closed forms,
 * so there is no Gram-matrix eigendecomposition. The orbit is generated by BFS,
 * deduped, and projected to a flat disk mesh (Klein = straight geodesics, the
 * honest choice for straight-edged triangles; Poincaré optional).
 */

import { Vector3 } from 'three';
import type { ParsedMesh } from '../types.ts';

export type DiskModel = 'klein' | 'poincare';

export interface TriangleGroupOptions {
  p: number;
  q: number;
  r: number;
  /** Number of reflection rounds (extent of the patch). */
  depth: number;
  /** Disk projection. Default 'klein' (geodesics are straight chords). */
  model?: DiskModel;
  /** Overall scale of the disk. Default 2.4. */
  scale?: number;
  /** Drop triangles whose disk-projected centroid exceeds this radius. Default 0.96. */
  maxRadius?: number;
}

// ── Minkowski form ⟨u,v⟩ = ux·vx + uy·vy − uz·vz ───────────────

function mdot(a: Vector3, b: Vector3): number {
  return a.x * b.x + a.y * b.y - a.z * b.z;
}

/** Reflect v across the mirror with spacelike unit normal m: v − 2⟨v,m⟩m. */
function reflect(v: Vector3, m: Vector3): Vector3 {
  return v.clone().addScaledVector(m, -2 * mdot(v, m));
}

/** A vector Minkowski-orthogonal to both a and b (J then Euclidean cross). */
function mcross(a: Vector3, b: Vector3): Vector3 {
  const Ja = new Vector3(a.x, a.y, -a.z);
  const Jb = new Vector3(b.x, b.y, -b.z);
  return new Vector3().crossVectors(Ja, Jb);
}

/** Spacelike unit mirror normal of the geodesic through hyperboloid points a, b. */
function sideMirror(a: Vector3, b: Vector3): Vector3 {
  const w = mcross(a, b);
  return w.multiplyScalar(1 / Math.sqrt(Math.abs(mdot(w, w))));
}

/** Scale a vector onto the hyperboloid ⟨v,v⟩ = −1 with z > 0. */
function toHyperboloid(v: Vector3): Vector3 {
  const n2 = -mdot(v, v); // = z² − x² − y², positive for timelike
  const out = v.clone().multiplyScalar(1 / Math.sqrt(Math.abs(n2)));
  if (out.z < 0) out.multiplyScalar(-1);
  return out;
}

function project(v: Vector3, model: DiskModel, scale: number): Vector3 {
  // v on hyperboloid (z > 0). Klein: (x,y)/z ; Poincaré: (x,y)/(1+z).
  const denom = model === 'klein' ? v.z : 1 + v.z;
  return new Vector3((scale * v.x) / denom, 0, (scale * v.y) / denom);
}

// ── Hashing for dedup ──────────────────────────────────────────

function key(v: Vector3, precision = 6): string {
  const f = Math.pow(10, precision);
  return `${Math.round(v.x * f) / f},${Math.round(v.y * f) / f},${Math.round(v.z * f) / f}`;
}

function centroidKey(tri: Vector3[]): string {
  const c = new Vector3();
  for (const v of tri) c.add(v);
  return key(c.multiplyScalar(1 / 3));
}

// ── Generator ──────────────────────────────────────────────────

export function makeTriangleGroupMesh(options: TriangleGroupOptions): ParsedMesh {
  const { p, q, r, depth } = options;
  const model = options.model ?? 'klein';
  const scale = options.scale ?? 2.4;
  const maxRadius = options.maxRadius ?? 0.96;

  if (1 / p + 1 / q + 1 / r >= 1 - 1e-9) {
    throw new Error(`(${p},${q},${r}) is not hyperbolic (need 1/p+1/q+1/r < 1)`);
  }

  // Three mirror normals, spacelike unit, built directly from the angles.
  const m0 = new Vector3(1, 0, 0);
  const m1 = new Vector3(-Math.cos(Math.PI / q), Math.sin(Math.PI / q), 0);
  const x = -Math.cos(Math.PI / p);
  const y = (-Math.cos(Math.PI / r) + Math.cos(Math.PI / q) * x) / Math.sin(Math.PI / q);
  const m2 = new Vector3(x, y, Math.sqrt(Math.max(0, x * x + y * y - 1)));

  // Fundamental triangle: vertex i is Minkowski-⊥ to the other two mirrors.
  const v0 = toHyperboloid(mcross(m1, m2));
  const v1 = toHyperboloid(mcross(m2, m0));
  const v2 = toHyperboloid(mcross(m0, m1));

  // BFS orbit with face + vertex dedup and a disk-radius cutoff.
  const vertices: Vector3[] = [];
  const faces: number[][] = [];
  const vertexIds = new Map<string, number>();
  const seenFaces = new Set<string>();
  const r2 = (maxRadius * scale) ** 2;

  const vertexId = (v: Vector3): number => {
    const k = key(v);
    let id = vertexIds.get(k);
    if (id === undefined) {
      id = vertices.length;
      vertexIds.set(k, id);
      vertices.push(project(v, model, scale));
    }
    return id;
  };

  const withinDisk = (tri: Vector3[]): boolean => {
    const c = new Vector3();
    for (const v of tri) c.add(project(v, model, scale));
    c.multiplyScalar(1 / 3);
    return c.x * c.x + c.z * c.z <= r2;
  };

  const addFace = (tri: Vector3[]): boolean => {
    const ck = centroidKey(tri);
    if (seenFaces.has(ck)) return false;
    if (!withinDisk(tri)) return false;
    seenFaces.add(ck);
    faces.push(tri.map(vertexId));
    return true;
  };

  let frontier: Vector3[][] = [[v0, v1, v2]];
  addFace(frontier[0]);

  for (let d = 0; d < depth; d++) {
    const next: Vector3[][] = [];
    for (const [a, b, c] of frontier) {
      // Reflect across each of the triangle's OWN three sides → its three
      // neighbours. The two shared vertices stay; the opposite one reflects.
      // The shared edge is written reversed so winding stays consistent
      // (so adjacent faces pair into twins).
      const neighbours: Vector3[][] = [
        [b, a, reflect(c, sideMirror(a, b))], // across edge a-b (opposite c)
        [c, b, reflect(a, sideMirror(b, c))], // across edge b-c (opposite a)
        [a, c, reflect(b, sideMirror(c, a))], // across edge c-a (opposite b)
      ];
      for (const img of neighbours) {
        if (addFace(img)) next.push(img);
      }
    }
    frontier = next;
    if (frontier.length === 0) break;
  }

  return { vertices, faces };
}
